Repository ardevd/ha-dimo, pull requests merged in 2024-12, with the labels that each got.

#58 feat: added signal defition for distance with MIL
  custom_components/dimo/const.py
Labels: enhancement

#60 feat: implemented DIMO-level sensor support
  custom_components/dimo/__init__.py
  custom_components/dimo/base_entity.py
  custom_components/dimo/binary_sensor.py
  custom_components/dimo/const.py
  custom_components/dimo/device_tracker.py
  custom_components/dimo/diagnostics.py
  custom_components/dimo/dimoapi/dimo_client.py
  custom_components/dimo/sensor.py
Labels: enhancement

#62 refactor: added a few sensor icon specifications
  custom_components/dimo/const.py
Labels: enhancement

#61 fix: DIMO is all uppercase.
  custom_components/dimo/__init__.py
Labels: bug

#63 feat: added api query for total wallet token rewards
  custom_components/dimo/dimoapi/dimo_client.py
Labels: enhancement

#65 refactor: refactored rewards query to be per-vehicle.
  custom_components/dimo/dimoapi/dimo_client.py
Labels: enhancement

#66 feat: added vehicle token rewards sensor
  custom_components/dimo/__init__.py
  custom_components/dimo/const.py
Labels: enhancement

#67 docs: added method docstrings for dimo_client.
  custom_components/dimo/dimoapi/dimo_client.py
Labels: documentation

#69 refactor: centralize graphql queries, improved token handling
  custom_components/dimo/dimoapi/dimo_client.py
  custom_components/dimo/dimoapi/queries.py
  tests/test_dimo_client.py
Labels: enhancement

#70 refactor: minor refactoring of auth.
  custom_components/dimo/dimoapi/auth.py
Labels: enhancement

#71 refactor: added a few sensor icons and powertrain sensor def
  custom_components/dimo/const.py
Labels: enhancement

#68 deps: bump dimo sdk to v0.0.7
  custom_components/dimo/manifest.json
  requirements_test.txt
Labels: DIMO, upstream

#73 refactor: updated version info for v0.1.0
  custom_components/dimo/manifest.json
  hacs.json
  sonar-project.properties
Labels: enhancement

#74 docs: updated HACS installation instructions
  README.md
Labels: documentation

#75 refactor: removed noisy debug logging
  custom_components/dimo/dimoapi/auth.py
  custom_components/dimo/dimoapi/dimo_client.py
Labels: enhancement

#76 refactor: added EV Battery SoH sensor definition
  custom_components/dimo/const.py
Labels: enhancement

#77 refactor: added sensor definition for EV battery voltage
  custom_components/dimo/const.py
Labels: enhancement

#82 refactor: added EV Battery temperature sensor definition
  custom_components/dimo/const.py
Labels: enhancement

#84 feat: added sensor definitions standard for Teslas.
  custom_components/dimo/const.py
Labels: enhancement

#86 refactor: retrieve signal data with concurrency
  custom_components/dimo/__init__.py
Labels: enhancement

#87 refactor: retrieve initial available signals for vehicles concurrently.
  custom_components/dimo/__init__.py
Labels: enhancement

#88 refactor: fetch DIMO sensor data in parallel.
  custom_components/dimo/__init__.py
Labels: enhancement

#89 refactor: Updated README.
  README.md
Labels: documentation

#90 fix: fixed exception message typos
  custom_components/dimo/__init__.py
Labels: bug

#91 refactor: replaced loguru with standard logging.
  custom_components/dimo/dimoapi/auth.py
  custom_components/dimo/dimoapi/dimo_client.py
  custom_components/dimo/manifest.json
  requirements_test.txt
Labels: enhancement

#92 refactor: added more type hinting to auth class
  custom_components/dimo/dimoapi/auth.py
Labels: enhancement

#93 refactor: removed unused time import from auth
  custom_components/dimo/dimoapi/auth.py
Labels: qa

#94 refactor: store only the privileged token string.
  custom_components/dimo/dimoapi/auth.py
  custom_components/dimo/dimoapi/dimo_client.py
  tests/test_auth.py
  tests/test_dimo_client.py
Labels: qa

#96 refactor: manage access token expiration
  custom_components/dimo/dimoapi/auth.py
  tests/test_auth.py
Labels: enhancement

#97 feat: added sensor definition for transmission temperature
  custom_components/dimo/const.py
Labels: enhancement
